import type { Npc } from '../types/npc.types'

export const NPC_SEED: Npc[] = [
  {
    id: '041866b7-3544-4523-b3ec-f72c87f5641a',
    name: 'Galdor',
    faction: 'Independente',
    status: 'vivo',
    description: 'Membro do Conselho Mercante',
    notes: 'Mestre das Especiarias',
    imageUrl: 'https://drive.google.com/thumbnail?id=1URH5CTIQyWOr6J3kE6SvdWWCHTvIpdPT&sz=w800',
    imagePosition: 'center',
  },
  {
    id: '006e76a5-89d2-492e-bd09-009f44245b84',
    name: 'Diaba',
    faction: 'Culto do Dragão',
    status: 'vivo',
    description: '11ª Asa do Culto do Dragão',
    notes: 'Localização desconhecida',
    imageUrl: 'https://drive.google.com/thumbnail?id=1uA3kr2lxTh1SRaIm6G4V6E94gjxL7FmM&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '6e00d856-5f29-41d5-8d7e-40a105658f2b',
    name: 'Patrichia',
    faction: 'Harpers',
    status: 'vivo',
    description: 'Amiga de Samael | Atualmente reside em Iriaebor | Mãe de Beleor | Avó de Bela',
    notes: 'Possui o Codice Dragonico / Uma parte do Mapa das 12 Canções',
    imageUrl: 'https://drive.google.com/thumbnail?id=1IG-XOpRRdxLLCnuJPnX0OU30Ax8layDv&sz=w800',
    imagePosition: 'top',
  },
  {
    id: 'dc198de8-3a3e-44ba-8720-3e173e3475f4',
    name: 'Vortak',
    faction: 'Culto do Dragão',
    status: 'vivo',
    description: '6ª Asa do Culto do Dragão',
    notes: 'Localização desconhecida',
    imageUrl: 'https://drive.google.com/thumbnail?id=18d47EVYaO2d8VHgw-N95iwfd5cLlpn2q&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '826f6728-3d07-4a10-95e3-d6e74d2c3a80',
    name: 'Traitos Rednose',
    faction: 'Independente',
    status: 'vivo',
    description: 'Membro do Conselho Mercante',
    notes: 'Mestre da Moeda',
    imageUrl: 'https://drive.google.com/thumbnail?id=1vsIKHZY8yBgWII1cWxleRnkqM8kRt90Q&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '7970e12f-f211-4c06-a5e4-e1f6f21e3e37',
    name: 'Balasar Gearbrand',
    faction: 'Independente',
    status: 'vivo',
    description: 'Membro do Conselho Mercante',
    notes: 'Mestre da Logística',
    imageUrl: 'https://drive.google.com/thumbnail?id=15hgOjb0paKoQdNI3JElE0kZCltFwi60Q&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '176c2c20-3763-4c4c-88e4-f04f1d3e95f7',
    name: 'Beleor',
    faction: 'Harpers',
    status: 'vivo',
    description: '',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1fcWECwSwg-6-2BY7NLlq2-Q1Ax0Z5lQ4&sz=w800',
    imagePosition: 'center',
  },
  {
    id: '79144f5d-b09f-4f95-835c-5c87bf8e68ac',
    name: 'Asthok Boca Mole',
    faction: 'Independente',
    status: 'vivo',
    description: 'Ladino',
    notes: 'Guilda Shadow Skulls',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Ez4ZLyih0JkU4I4tCijbIhGYLdvGjHvS&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '610e4caa-98b5-4cbe-ab57-68c30f61f418',
    name: 'Assassino',
    faction: 'Confraria da Lâmina Velada',
    status: 'morto',
    description: 'Assassino contratado para invadir a torre do Mago Kaldrin',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1TTWX_CqGP2-4pNvU36nTlkZkiK0fZofY&sz=w800',
    imagePosition: 'top',
  },
  {
    id: 'e8c334af-05bb-4dcf-ad80-d72302a4d92b',
    name: 'Bener Baba',
    faction: 'Independente',
    status: 'vivo',
    description: 'Membro do Conselho Mercante',
    notes: 'Mestre das Manufaturas',
    imageUrl: 'https://drive.google.com/thumbnail?id=1hoKrQuFZCJe3a5ChysQgYq5a855n8O9q&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '2e464047-8ed3-412a-8dd0-0586a5c70574',
    name: 'Caldrous',
    faction: 'Culto do Dragão',
    status: 'morto',
    description: 'Clérigo de Tiamat',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1RdAFCB5lcCTYaciom8CYMvWn7Dwjy8nV&sz=w800',
    imagePosition: 'top',
  },
  {
    id: 'eef428ab-a43c-47c1-8fa6-879b7e88b61b',
    name: 'Capitão Roderic Vanneth',
    faction: 'Independente',
    status: 'vivo',
    description: 'Capitão da Espira Oeste',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1s9MYdfCCgFtTmIkZg3xVLgt_sBNmw2kO&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '5c6eb043-4c91-4cde-9af2-3af3f0f3d11c',
    name: 'Derek Duas Facas',
    faction: 'Culto do Dragão',
    status: 'morto',
    description: 'Amigo de Asthok Boca Mole',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=11BhJk4Fe_8cBJVFugpx-J4uk06kJ__Wb&sz=w800',
    imagePosition: 'top',
  },
  {
    id: 'ffac2ccc-d21e-43ac-a543-871d713b75ed',
    name: 'Ellyn Moonwhisper',
    faction: 'Harpers',
    status: 'vivo',
    description: 'High Harper',
    notes: 'Lua da Informação',
    imageUrl: 'https://drive.google.com/thumbnail?id=1pidXSvJTOH6JpzX5-ITq3bJAWslURWpG&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '79bffc3c-51f8-4870-b315-eff89ffae788',
    name: 'Kandaelis',
    faction: 'Independente',
    status: 'vivo',
    description: 'Braço direito do Galdor',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1zkTPxL5h9Et94AtOUWyTQo70jauEClxF&sz=w800',
    imagePosition: 'top',
  },
  {
    id: '715c23d1-3e72-4a6f-afe7-80c64849f422',
    name: 'Lorde Bronn',
    faction: 'Independente',
    status: 'vivo',
    description: 'Atual governante de Iriaebor',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1IBgZDVohq34_S1Tph1Cq3aiOy57iHU_6&sz=w800',
    imagePosition: 'top',
  },
  {
    id: 'f1f0a14f-9076-4169-8f34-45594bebefbb',
    name: 'Lyra Vindariel',
    faction: 'Independente',
    status: 'vivo',
    description: 'Princesa de Iriaebor',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1X3g9I2lfz-BWAGAcWVJDFMMR5dUzHfzX&sz=w800',
    imagePosition: 'top',
  },
  {
    id: 'ca437098-d01f-446a-be47-8aac96328a26',
    name: 'Merelin',
    faction: 'Independente',
    status: 'vivo',
    description: '',
    notes: 'Guilda Shadow Skulls',
    imageUrl: 'https://drive.google.com/thumbnail?id=1wlDsPVYFw9Y2qLk4aJ1UMeMD-hIJfx2Q&sz=w800',
    imagePosition: 'top',
  },
  {
    id: 'f967f2ef-9cba-401d-a8f1-cf541eb6c4d5',
    name: 'Ornn',
    faction: 'Independente',
    status: 'vivo',
    description: 'Ferreiro da Cidade Alta',
    notes: '',
    imageUrl: 'https://drive.google.com/thumbnail?id=1SH75rOyABJm6TfxP3QUkkx0xp3AN2qUh&sz=w800',
    imagePosition: 'top',
  },
]
