export interface RandomTable {
  id: string
  category: string
  title: string
  entries: string[]
}

export const RANDOM_TABLES: RandomTable[] = [
  // ── Encontros ──────────────────────────────────────────────────────────────
  {
    id: 'encontro-floresta',
    category: 'Encontros',
    title: 'Encontro — Floresta',
    entries: [
      '2d4 goblins carregam sacos de mantimentos roubados de uma aldeia próxima',
      'Um lobo enorme observa o grupo das sombras — não ataca a menos que provocado',
      'Uma cabana abandonada com fumaça saindo da chaminé ainda quente',
      'Rastros frescos de urso-coruja cruzaram o caminho há menos de uma hora',
      'Um elfo solitário medita ao pé de uma árvore com runas entalhadas',
      'Armadilhas de caçador camufladas entre as folhas (Percepção CD 14)',
      'Um mercador perdido com mula sobrecarregada — oferece ouro por orientação',
      'Uma fada espia o grupo de cima, some antes de ser confrontada',
      'Acampamento destruído — rastros indicam fuga em pânico em várias direções',
      'Um druida com flecha no ombro pede ajuda urgente, não explica de quem fugiu',
      'Sons de batalha à distância — coluna de fumaça sobe entre as copas',
      "Uma poça d'água reflete um céu estrelado mesmo sob sol pleno",
      '1d6 bandidos preparam emboscada no estreitamento do caminho à frente',
      'Uma planta carnívora gigante disfarçada de arbusto colorido',
      'Uma criança nobre sozinha, desorientada, sem saber como chegou aqui',
      'Pegadas de gigante que seguem a mesma direção do grupo faz dois dias',
    ],
  },
  {
    id: 'encontro-dungeon',
    category: 'Encontros',
    title: 'Encontro — Dungeon',
    entries: [
      'Um zumbi patrulheiro carrega uma lanterna ainda acesa — sem motivação aparente',
      'Armadilha de dardo envenenado na altura dos olhos (Percepção CD 13)',
      'Marcas de garras recentes nas paredes — algo grande passou há pouco',
      'Um tesouro-baú disfarçado de caixa comum aguarda vítimas descuidadas',
      'Vozes em Infracomum discutem com raiva por trás de uma porta trancada',
      'Cheiro de enxofre precede um demônio menor explorando o corredor',
      'Uma fonte de pedra com água que cura 1d4 PV — apenas uma vez por descanso',
      'Um rato enorme carrega uma moeda de ouro reluzente para seu ninho',
      'Esqueletos de aventureiros com equipamentos ainda utilizáveis',
      'Um espelho que mostra o passado do cômodo em vez do reflexo atual',
      'Um prisioneiro acorrentado que pode ser aliado genuíno ou isca',
      '2d6 kobolds montando uma nova armadilha elaborada, absortos no trabalho',
      'O chão desmorona parcialmente sob o personagem mais pesado (Atletismo CD 12)',
      'Um fantasma repete em loop o último momento de sua morte',
      'Câmara com paredes que se fecham lentamente (Investigação CD 11 para travar)',
      'Um oráculo morto-vivo que responde três perguntas antes de descansar',
    ],
  },
  {
    id: 'encontro-cidade',
    category: 'Encontros',
    title: 'Encontro — Cidade',
    entries: [
      'Um batedores de carteira esbarra no personagem com maior Percepção passiva',
      'Arauto anuncia recompensa por fugitivos — a descrição combina com um dos PJs',
      'Briga de taberna transborda para a rua, envolve um NPC importante',
      'Nobre bêbado oferece emprego absurdo por quantidade generosa de ouro',
      'Um culto distribui panfletos sobre sinais do fim dos tempos',
      'Guardas param o grupo para verificação de identidade sem dar motivo',
      'Vendedor ambulante vende "poções de cura" — são água salgada com corante',
      'Uma criança oferece guiar o grupo em troca de uma refeição quente',
      'Carruagem em alta velocidade quase atropela os aventureiros na curva',
      'Um mago velho busca assistentes para missão "completamente segura"',
      'O mestre de uma guilda local pede um favor discreto e urgente',
      'Incêndio começa em prédio próximo — gritos de criança são ouvidos',
      'Mensageiro entrega carta ao aventureiro errado com urgência militar',
      'Festival local bloqueia todas as ruas principais por horas',
      'Um espião que o grupo acreditava morto reaparece no mercado',
      'Uma guilda criminosa recruta discretamente — cartaz com linguagem codificada',
    ],
  },

  // ── Clima & Ambiente ───────────────────────────────────────────────────────
  {
    id: 'clima',
    category: 'Clima & Ambiente',
    title: 'Clima',
    entries: [
      'Céu aberto e vento suave — condições ideais para viagem',
      'Neblina densa ao amanhecer — visibilidade reduzida a 6 metros até o meio-dia',
      'Chuva fina e constante — trilhas ficam lamacentas, rastros somem em 1 hora',
      'Tempestade elétrica à noite — raios revelam silhuetas suspeitas',
      'Calor sufocante — cada hora de marcha forçada exige teste de Constituição CD 10',
      'Frio cortante com vento forte — movimento reduzido, nenhum descanso curto na área aberta',
      'Neve leve cobre o solo — rastros ficam perfeitamente preservados por horas',
      'Nevasca repentina bloqueia o caminho — aguardam 1d4 horas ou desviam',
      'Nuvens carregadas ameaçam chuva — chegam em 2d6 horas',
      'Névoa de cor levemente roxa que não se dissipa — origem desconhecida',
      'Granizo repentino causa 1 de dano por rodada fora de abrigo',
      'Sol forte e seco — poeira levantada revela movimento à distância',
      'Vento norte carrega cheiro incomum para a região — pressagio',
      'Tempo perfeito demais — silêncio absoluto, nenhum pássaro',
      'Chuva vermelha cobre tudo por alguns minutos — deixa mancha que some depois',
    ],
  },
  {
    id: 'sons-dungeon',
    category: 'Clima & Ambiente',
    title: 'Ambiência — Dungeon',
    entries: [
      'Gotejamento rítmico de água vindo de corredor lateral',
      'Lamento baixo e distante que cessa ao menor barulho',
      'Cheiro forte de carne podre de origem não identificada',
      'Corrente de ar frio de direção incerta — há abertura próxima',
      'Chão ressoa diferente sob passos — câmara vazia logo abaixo',
      'Cheiro de enxofre e metal superaquecido',
      'Risadas abafadas atrás de uma parede de pedra completamente sólida',
      'Barulho rítmico de martelos — alguém ainda trabalha aqui',
      'Silêncio absoluto repentino — algo parou de se mover ao ouvir o grupo',
      'Vento sussurra um nome diferente para cada personagem',
      'Cheiro de fumaça antiga — houve um grande incêndio décadas atrás',
      'Rangido de correntes pesadas sem fonte visível',
      'Passos que espelham exatamente os do grupo — sempre atrás',
      'Cheiro forte de terra molhada — inundação recente ou poço muito próximo',
      'Respiração lenta e profunda vinda do teto — algo grande dorme acima',
    ],
  },

  // ── Nomes de NPCs ─────────────────────────────────────────────────────────
  {
    id: 'nome-humano',
    category: 'Nomes de NPCs',
    title: 'Nome — Humano',
    entries: [
      'Aldric Fontaine',
      'Mira Soldado',
      'Tomas Bravel',
      'Sera Dunmore',
      'Edwyn Ashford',
      'Nora Castelo',
      'Gareth Holm',
      'Lena Farrow',
      'Osman Drak',
      'Isla Mercer',
      'Percival Stone',
      'Dara Wynne',
      'Roland Finch',
      'Sable Crowe',
      'Corvin Marsh',
      'Aine Dunbar',
      'Leoric Voss',
      'Brynn Hale',
      'Mattis Colter',
      'Wren Aldgate',
      'Caelan Frost',
      'Rhea Emberton',
      'Dorian Vale',
      'Seren Blackwood',
    ],
  },
  {
    id: 'nome-elfico',
    category: 'Nomes de NPCs',
    title: 'Nome — Élfico',
    entries: [
      'Aelindra Silvathorn',
      'Caelith Moonwhisper',
      'Sylara Dawnweave',
      'Erindel Starfall',
      'Thalion Greyleaf',
      'Mirae Windveil',
      'Aldanis Brightwood',
      'Seraniel Evensong',
      'Liriel Ashbough',
      'Faendrel Sunshard',
      'Arannis Duskwalker',
      'Yrael Emberveil',
      'Cylara Moonsong',
      'Galadhor Swiftbranch',
      'Naeris Starweave',
      'Fenriel Goldenleaf',
      'Sariel Nightbloom',
      'Theren Clearwater',
      'Quelenna Dawnpetal',
      'Adran Misthollow',
    ],
  },
  {
    id: 'nome-anao',
    category: 'Nomes de NPCs',
    title: 'Nome — Anão',
    entries: [
      'Throdin Ironmantle',
      'Brega Stonefist',
      'Kordak Hammerfall',
      'Dugra Ashbeard',
      'Vondal Coppervein',
      'Thora Goldpick',
      'Barendd Deepdelve',
      'Marta Ironbrew',
      'Harbek Coalforge',
      'Rikka Stonehew',
      'Gundren Runeaxe',
      'Helga Deepstone',
      'Orsik Boulderback',
      'Nora Ironsong',
      'Adrik Gravelwarden',
      'Vistra Coppercloak',
      'Travok Stonehammer',
      'Dagnal Ironfoot',
      'Bruenor Cragback',
      'Tordek Deepvein',
    ],
  },
  {
    id: 'nome-antagonista',
    category: 'Nomes de NPCs',
    title: 'Nome — Antagonista / Misterioso',
    entries: [
      'Malachar o Silêncio',
      'Syreth das Cinzas',
      'Valdris Noite-Funda',
      'A Senhora sem Rosto',
      'Kethris o Vermelho',
      'Zorra do Abismo',
      'O Arconte Pálido',
      'Sevryn Corrompido',
      'Nythara a Dívida',
      'Drath Osso-Negro',
      'Elara Sombra-do-Amanhecer',
      'Mordecai Venenosa',
      'O Vigésimo Terceiro',
      'Thrax o Faminento',
      'Isera Chama-Morta',
      'Valoren o Esquecido',
      'Korrath do Crepúsculo',
      'A Mão que Não Sangra',
    ],
  },

  // ── Loot & Tesouros ────────────────────────────────────────────────────────
  {
    id: 'loot-comum',
    category: 'Loot & Tesouros',
    title: 'Loot — Comum',
    entries: [
      '2d6 peças de ouro numa bolsa de couro rasgada',
      'Mapa marcado com um X em local não identificado',
      'Poção de Cura (2d4+2 PV) bem conservada',
      'Anel de prata simples com iniciais gravadas — VI',
      'Diário parcialmente queimado com entradas dos últimos 30 dias',
      '6 tochas e um isqueiro de pederneira',
      'Faca de caça de boa qualidade — nítida e balanceada',
      'Rações de viagem para 1d4 dias',
      'Carta lacrada endereçada a alguém numa cidade próxima',
      'Espelho de bronze polido do tamanho da palma da mão',
      'Corda de 15 metros, trançada, bem conservada',
      '1d4+2 flechas com plumas vermelhas pouco comuns',
      'Medalhão com retrato pintado de uma família nobre',
      '3d10 peças de prata misturadas com areia e detritos',
      'Livro de orações de divindade com páginas arrancadas no fim',
      'Chave de formato incomum sem fechadura correspondente',
      'Frasco de tinta invisível e pena de escrita',
      'Botas gastas com fundo falso contendo 8 peças de ouro',
    ],
  },
  {
    id: 'loot-raro',
    category: 'Loot & Tesouros',
    title: 'Loot — Raro / Mágico',
    entries: [
      'Espada Longa +1 — runas élficas brilham levemente no escuro',
      'Anel da Proteção +1 — requer sintonização',
      'Poção de Invisibilidade — dura 1 hora ou até atacar',
      'Varinha com 1d6+1 cargas de Míssil Mágico',
      'Botas Élficas — não deixa rastros em superfícies naturais',
      'Pedra da Sorte — uma vez por dia, relance um teste qualquer',
      'Adaga das Sombras — +2d6 de dano quando em vantagem no ataque',
      'Capa do Mago — +1 CA, regula a temperatura do usuário',
      'Par de Orbes de Comunicação — alcance de 10 km',
      'Pergaminho com magia de 3° círculo a critério do mestre',
      'Amuleto da Saúde — máximo de PV +5 enquanto equipado',
      'Óculos da Noite — visão no escuro até 18 metros',
      'Luvas do Prestidigitador — +2 em testes de Mãos Ágeis',
      'Espelho da Revelação — mostra criaturas invisíveis em 9 metros',
      'Pedra de Ânimo — imunidade a medo enquanto mantida na mão',
      'Bracelete do Escudo — uma vez por dia, lança Escudo como reação',
      'Símbolo Sagrado que pulsa ao detectar mortos-vivos num raio de 9 m',
      'Bolsa de Dar — qualquer objeto colocado dentro pesa metade',
    ],
  },

  // ── NPCs ──────────────────────────────────────────────────────────────────
  {
    id: 'personalidade-npc',
    category: 'NPCs',
    title: 'Personalidade de NPC',
    entries: [
      'Excessivamente desconfiado — pergunta nome e intenção várias vezes',
      'Otimista ao extremo mesmo em situações desesperadoras',
      'Fala sempre em sussurros e olha para os lados o tempo todo',
      'Conta histórias longuíssimas antes de chegar ao ponto relevante',
      'Colecionador obsessivo — quer algo em troca de qualquer informação',
      'Pragmático frio — decide tudo por custo-benefício sem emoção',
      'Supersticioso — faz gestos de proteção ao ouvir menção de magia',
      'Honesto ao ponto de ser rude sem perceber o impacto das palavras',
      'Nostálgico incurável — tudo remete a uma história da infância',
      'Ansioso e nervoso, mas extremamente competente no trabalho',
      'Arrogante com estranhos, leal até a morte com quem conhece bem',
      'Filosófico — questiona o significado moral de cada pedido',
      'Entusiasta genuíno — se empolga com qualquer assunto novo com igual fervor',
      'Melancólico — carrega um segredo pesado, pesa nas entrelinhas',
      'Usa humor constante para desviar de qualquer assunto sério',
      'Impaciente — interrompe frases, termina raciocínios alheios erradamente',
    ],
  },
  {
    id: 'aparencia-npc',
    category: 'NPCs',
    title: 'Aparência de NPC',
    entries: [
      'Cicatriz em forma de garra cobrindo o lado esquerdo do rosto',
      'Olhos de cores diferentes — um âmbar e um acinzentado',
      'Cabelo completamente branco apesar de aparentar menos de 30 anos',
      'Dentes de ouro que reluzem quando sorri',
      'Tatuagem de serpente que sobe desde o pulso até o pescoço',
      'Três dedos da mão esquerda substituídos por ganchos de bronze',
      'Andar mancante mas postura ereta e imponente',
      'Roupas sempre impecáveis independente de qualquer circunstância',
      'Barba ou cabelo trançado com contas de madeira pintadas',
      'Olheiras fundas — claramente não dorme bem há várias semanas',
      'Marca de nascença em formato de estrela de quatro pontas no pescoço',
      'Extremamente baixo ou alto para a raça — notado imediatamente',
      'Voz rouca e grave que contrasta com aparência jovial e delicada',
      'Pele com reflexo levemente prateado sob luz forte',
      'Acompanhado de um animal incomum que o segue por toda parte',
      'Mãos com calos enormes — trabalhou muito com ferramentas a vida toda',
    ],
  },
  {
    id: 'motivacao-npc',
    category: 'NPCs',
    title: 'Motivação de NPC',
    entries: [
      'Vingar a morte de um familiar assassinado há poucos meses',
      'Acumular riqueza para libertar escravos da cidade natal',
      'Provar valor para uma família nobre que o rejeitou por nascimento',
      'Encontrar cura para uma doença mágica que consome um ente querido',
      'Recuperar um artefato sagrado roubado do templo que serve',
      'Escapar de dívida impagável com uma guilda criminosa local',
      'Descobrir a verdade sobre o desaparecimento de ambos os pais',
      'Alcançar posto que foi negado por preconceito ou política',
      'Completar a obra inacabada de um mentor falecido',
      'Redimir erro do passado que custou vidas inocentes',
      'Proteger um segredo que derrubaria o governo se revelado',
      'Ganhar fama suficiente para que bardos cantem seu nome',
      'Reunir informações para um patrono misterioso cujo rosto nunca viu',
      'Encontrar um lugar seguro para a família em período de guerra',
      'Sobreviver mais um dia — tem inimigos muito mais poderosos',
      'Provar que a profecia que o persegue está errada sobre ele',
    ],
  },
  {
    id: 'defeito-npc',
    category: 'NPCs',
    title: 'Defeito / Segredo de NPC',
    entries: [
      'Traiu um antigo aliado para salvar a própria pele — ele sobreviveu',
      'É um informante pago pela facção oposta ao grupo',
      'Tem vício em uma substância que compromete o julgamento à noite',
      'Mentiu sobre o passado e agora não consegue manter as histórias coerentes',
      'Deve uma favor a um demônio menor — prazo se aproxima',
      'Roubou a identidade de alguém — a pessoa real pode aparecer',
      'Tem medo patológico de um elemento comum (água, fogo, espaços fechados)',
      'Não consegue resistir a apostar — já perdeu coisas que não eram suas',
      'Mandou alguém inocente para a morte por omissão calculada',
      'É membro secreto de um culto que considera benevolente',
      'Fingiu ser outra classe social a vida toda — não sabe como agir sem a máscara',
      'Fez pacto de sangue com um feiticeiro que pode cobrá-lo a qualquer momento',
      'Acredita piamente em uma mentira que afeta todas as suas decisões',
      'Tem um filho secreto que os inimigos usariam como refém se soubessem',
      'Está morrendo de doença que esconde de todos ao redor',
    ],
  },

  // ── Narrativa ──────────────────────────────────────────────────────────────
  {
    id: 'gancho-aventura',
    category: 'Narrativa',
    title: 'Gancho de Aventura',
    entries: [
      'Uma aldeia inteira acorda dormindo de pé — sem sinais de violência ou fuga',
      'Cartas chegam a adventureiros diferentes com o mesmo remetente — morto há 10 anos',
      'Um portal arcano abre no mercado central; algo sai arrastando uma criança',
      'O prefeito contrata silenciosamente assassinos para eliminar seus próprios guardas',
      'Um dragão pousa na cidade e pede para ingressar na guilda de aventureiros',
      'Crianças de bairros diferentes começam a desenhar o mesmo símbolo sem se conhecer',
      'Um mapa antigo indica que a cidade foi construída sobre uma prisão demoníaca',
      'O irmão de um PJ aparece sem memória dos últimos três anos',
      'Uma torre mágica surge do nada em floresta proibida, com luz acesa lá dentro',
      'Todos os animais da região fogem na mesma direção há dois dias',
      'Um culto oferece cura milagrosa genuína — mas os curados mudam de personalidade',
      'A estátua do herói fundador chora sangue toda meia-noite por três dias seguidos',
      'Um mensageiro morre entregando um pacote que ninguém na cidade encomendou',
      'A guilda dos ladrões pede ajuda a paladinos — algo abaixo da cidade os aterroriza',
      'Uma profecia antiga se cumpriu pela metade — a segunda parte é catastrófica',
      'O rio para de fluir durante a noite e retorna de manhã com cor diferente',
    ],
  },
  {
    id: 'evento-taverna',
    category: 'Narrativa',
    title: 'Evento de Taverna',
    entries: [
      'Briga eclode por partida de dados — um dos jogadores acusa trapaça com razão',
      'Um bardo entoa música que faz todos chorarem sem saber por quê',
      'Homem encapuzado oferece trabalho arriscado por ouro excessivo em voz baixa',
      'Alguém reconhece um PJ de um episódio passado inconveniente e grita o nome',
      'O taverneiro confessa um crime para estranho — pensando que é um sacerdote',
      'Uma mulher entra ensanguentada, diz uma frase e desmaia no chão',
      'Um anão desafia o grupo mais forte para braço de ferro pelo privilégio de pagar a conta',
      'Rumor de tesouro nas ruínas fora da cidade passa de mesa em mesa com detalhes crescentes',
      'O cozinheiro encontra ingrediente suspeito enviado por fornecedor novo essa semana',
      'Duelo de insultos poéticos entre dois nobres que escala rapidamente para espadas',
      'Filho de nobre bêbado ofende inadvertidamente todos os aventureiros à mesa',
      'Um viajante mostra mapa que contradiz completamente a geografia local aceita',
      'O vinho de um barril está envenenado — Constituição CD 12 ou fica enfermo',
      'Um fantasma senta à mesa vazia ao lado do grupo — visível apenas para um PJ',
      'Um torneio de contos de horror começa — o vencedor tem a conta paga pelo mestre',
    ],
  },
  {
    id: 'complicacao',
    category: 'Narrativa',
    title: 'Complicação Inesperada',
    entries: [
      'A pessoa que o grupo precisava encontrar foi presa esta manhã',
      'O objeto da missão foi roubado antes da chegada do grupo',
      'Um aliado está sendo chantageado e sabota a missão involuntariamente',
      'A rota planejada foi bloqueada por disputa territorial recente',
      'Um terceiro grupo completamente diferente busca o mesmo objetivo',
      'A recompensa sumiu junto com o contratante — sem rastro',
      'O vilão tem como refém alguém que o grupo conhece pessoalmente',
      'O sucesso da missão prejudicaria diretamente uma comunidade inocente',
      'Magia não funciona na área — razão completamente desconhecida',
      'Um membro do grupo é reconhecido como fugitivo local procurado',
      'O informante só fala em troca de favor muito mais perigoso do que a missão',
      'Reforço inimigo chega antes do previsto — o plano precisa mudar agora',
      'A testemunha principal foi comprada e vai mentir de forma convincente',
      'O item mágico tem efeito colateral grave que ninguém havia mencionado antes',
      'Um dos NPCs aliados esconde lealdade ao lado oposto desde o início',
      'Chega um representante da lei que deve satisfações antes de qualquer ação',
    ],
  },
  {
    id: 'rumor',
    category: 'Narrativa',
    title: 'Rumor de Taverna',
    entries: [
      '"O lorde desta região faz pacto com demônios toda lua nova — vi as chamas"',
      '"A velha mina abandonada voltou a ter luz à meia-noite já faz uma semana"',
      '"O filho do ferreiro sumiu sem deixar rastro. Dizem que a floresta o chamou"',
      '"Há túnel secreto que liga o castelo à margem do rio — só nobres sabem da entrada"',
      '"A guilda dos mercadores compra crianças com dom para magia antes dos 5 anos"',
      '"O capitão da guarda foi substituído. O novo não é humano, eu juro pelos deuses"',
      '"Encontraram um dragão morto nas montanhas — o que mata dragões ainda está lá?"',
      '"A estrada ao norte está amaldiçoada — três caravanas desapareceram em um mês"',
      '"Um anão chegou do leste com ouro demais e perguntas de menos sobre a cidade"',
      '"A estátua na praça se mexe quando todos olham para o outro lado"',
      '"O templo de Pelor recusa peregrinos há duas semanas sem dar qualquer explicação"',
      '"Vi elfos das sombras perto da cidade. Última vez que isso aconteceu houve guerra"',
      '"Há recompensa secreta por informações sobre um grupo chamado Os Sete Velados"',
      '"O velho eremita da colina estava certo — algo muito errado com o rio do norte"',
      '"Quem dorme no cruzamento das três estradas na lua cheia não acorda igual"',
      '"Dizem que o cemitério antigo tem uma lápide que muda de nome toda meia-noite"',
    ],
  },
  {
    id: 'missao-secundaria',
    category: 'Narrativa',
    title: 'Missão Secundária',
    entries: [
      'Recuperar uma herança familiar de uma mansão tomada por mortos-vivos',
      'Escoltar um mercador idoso até a cidade vizinha — ele sabe de algo valioso',
      'Investigar por que os animais de um fazendeiro estão morrendo em ordem',
      'Encontrar o filho de um nobre que fugiu para se tornar aventureiro',
      'Limpar uma mina de kobolds em troca da rota de passagem por território privado',
      'Recuperar um anel de noivado que foi parar no estômago de um dragão jovem',
      'Descobrir quem está envenenando o poço do bairro pobre há três dias',
      'Deter uma guerra de gangues antes do festival da cidade começar amanhã',
      'Entregar uma mensagem codificada sem ler o conteúdo — e resistir à tentação',
      'Capturar vivo um criminoso que o grupo encontrou e ignorou anteriormente',
      'Resolver uma disputa de terras entre duas famílias rivais sem derramamento de sangue',
      'Proteger um testemunho importante até o tribunal amanhã de manhã',
      'Descobrir o paradeiro de um artefato roubado há 30 anos de um museu',
      'Reparar a reputação de um herói falso que se tornou lenda local sem merecer',
      'Acompanhar um prisioneiro até a prisão — ele conhece os segredos do grupo',
    ],
  },
]

// ── Lookups pré-computados (calculados uma única vez no carregamento do módulo) ──

/** Categorias únicas na ordem em que aparecem no array. */
export const TABLE_CATEGORIES: string[] = [...new Set(RANDOM_TABLES.map((table) => table.category))]

/** Tabelas agrupadas por categoria. Evita filter() no render. */
export const TABLES_BY_CATEGORY: Readonly<Record<string, RandomTable[]>> = TABLE_CATEGORIES.reduce<
  Record<string, RandomTable[]>
>((acc, cat) => {
  acc[cat] = RANDOM_TABLES.filter((table) => table.category === cat)
  return acc
}, {})

/** Mapa id → tabela para lookup O(1) ao rolar. */
export const TABLES_BY_ID: Readonly<Record<string, RandomTable>> = Object.fromEntries(
  RANDOM_TABLES.map((table) => [table.id, table]),
)
